# added dist: trusty which is ubuntu 14 , because some packages in apt-packages.txt ie libblas3gf , liblapack3gf can
#  only be installed on ubuntu 14
dist: trusty
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo xargs -a apt-packages.txt apt-get install --fix-missing
install:
  - pip install -r base-requirements.txt
  - pip install -r dev-requirements.txt
  - sudo apt-get install python-matplotlib python-numpy python-scipy python-sklearn
  - pip install scikit-learn==0.20.4
  - pip install -e git+https://github.com/edx/nltk.git@2.0.6#egg=nltk
  - travis_retry ./download-nltk-corpus.sh
script:  nosetests
